version: '3.8'
services:
  app:
    image: composer:latest
    ports:
      - 8000:8000
    container_name: laravel_app-trabalho
    volumes:
      - /c/aulas_unesc_4-periodo/backend-framework/trabalho-bimestral/laravel:/var/www
    working_dir: /var/www
    networks:
      - laravel_network
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_trabalho_laravel
    restart: always
    environment:
      MYSQL_DATABASE: trabalho_laravel
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: 1234567
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:


networks:
  laravel_network:
    driver: bridge
